name: Build and Push Python Image to Google Cloud Platform

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: timeoff
      GOOGLE_PROJECT: local-concord-408802
    steps:

      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
          version: '>= 363.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'app-test'
          location: 'asia-northeast1'
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet
      - name: Push Docker Image to Container Registry (GCR)
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          IMAGE_TAG: $(git rev-parse HEAD)

        run: |
          docker build -t gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:$(git rev-parse HEAD) .
          docker push gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:$(git rev-parse HEAD)
      - name: 'Deploy to timeoff'
        env:
          IMAGE_TAG: $(git rev-parse HEAD)
        run: helm upgrade -i timeoff --create-namespace -n suresh --set image.tag=$(git rev-parse HEAD) ./_infra/helm/timeoff -f ./_infra/helm/timeoff/values/values.yaml

